// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateNotificationRequest defines model for CreateNotificationRequest.
type CreateNotificationRequest struct {
	Payload     map[string]interface{} `json:"payload"`
	RecipientId string                 `json:"recipient_id"`
	Type        string                 `json:"type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// NotificationResponse defines model for NotificationResponse.
type NotificationResponse struct {
	CreatedAt   time.Time              `json:"created_at"`
	Id          openapi_types.UUID     `json:"id"`
	Payload     map[string]interface{} `json:"payload"`
	RecipientId string                 `json:"recipient_id"`
	Status      string                 `json:"status"`
	Type        string                 `json:"type"`
}

// NotificationId defines model for NotificationId.
type NotificationId = string

// PostNotificationsJSONRequestBody defines body for PostNotifications for application/json ContentType.
type PostNotificationsJSONRequestBody = CreateNotificationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostNotifications Создать уведомление
	// (POST /notifications)
	PostNotifications(c *fiber.Ctx) error
	// GetNotificationsId Получить уведомление
	// (GET /notifications/{id})
	GetNotificationsId(c *fiber.Ctx, id NotificationId) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// PostNotifications operation middleware
func (siw *ServerInterfaceWrapper) PostNotifications(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PostNotifications(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetNotificationsId operation middleware
func (siw *ServerInterfaceWrapper) GetNotificationsId(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id NotificationId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetNotificationsId(c, id)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/notifications", wrapper.PostNotifications)

	router.Get(options.BaseURL+"/notifications/:id", wrapper.GetNotificationsId)

}
